version: '3.8'

services:
  notion-sync:
    build: .
    container_name: notion-sync
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount source code for development
      - .:/app
      # Mount X11 socket for desktop notifications (Linux/macOS)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Mount D-Bus for notifications
      - /var/run/dbus:/var/run/dbus:ro
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - PYTHONUNBUFFERED=1
    network_mode: host
    # For macOS, we might need different notification approach
    profiles:
      - dev

  # Production service without development mounts
  notion-sync-prod:
    build: .
    container_name: notion-sync-prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - prod 